add report

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -31,9 +31,10 @@ jobs:
         run: mvn -Dtest=OrderDishTests test
       - name: OrderProfile Test
         run: mvn -Dtest=OrderProfileTests test
-      - name: Export test results
-        run: cp CS4156_DrinkMoreWater/target/surefire-reports/*.txt CIResults
-      - uses: EndBug/add-and-commit@v7
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          add: CIReports/.
-          default_actor: github_actions
+          name: CI Tests report           # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
