Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -31,10 +31,8 @@ jobs:
         run: mvn -Dtest=OrderDishTests test
       - name: OrderProfile Test
         run: mvn -Dtest=OrderProfileTests test
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          name: CI Tests report           # Name of the check run which will be created
-          path: CIResults/jest-*.xml    # Path to test results
-          reporter: jest-junit        # Format of test results
+          name: test-results
+          path: jest-junit.xml
